### ISSUE TITLE
Problem with home assistant login

### ISSUE THREAD

**Issue by agabi10** [albertogeniola/Custom-Meross-Pairer#10]
I'm using the home assistant docker container with the mosquitto docker container as the MQTT broker.

I installed the Meross LAN integration through HACS. In the README.md file of this integration it says that this app can be used to bind the devices with our private MQTT broker to avoid using Meross cloud to use the device.

The problem I found is that regardless if I put the address of the Home Assistant container (and the credentials of Home Assistant) or the address of the mosquitto container (and the credentials of the mosquitto broker) it always displays a toast with the "No local HTTP service found".

What am I supposed to write in that field?

**Comment by DobleJSoto** [comment]
I have the same problem, i'm triying to solve.

**Comment by rcdailey** [comment]
The lack of documentation here is really frustrating. I can't get the login working either. I tried `http://homeassistant:1883`, for example, or even `https://homeassistant:8883` and it doesn't work. Also discovery isn't working, which I'm not sure why.

@albertogeniola can you offer some instruction here? Thank you.

**Comment by maxistviews** [comment]
From what I read over the last few days, homeassistant's Mqtt broker is no longer compatible with this stuff as it's using mqtt v6 without SQLite. There's a fork of mosquitto that does support it apparently. But to be honest it's all more trouble for me than it's worth. 

This could be false but that's what my current understanding is.

**Comment by albertogeniola** [comment]
Hi guys,
this app does not talk directly with HOME-ASSISTANT but allows you to pair Meross devices with third party brokers. So far, the only supported broker is [meross-lan](https://github.com/krahabb/meross_lan), although I'm currently developing a dedicated addon for HA to serve as dedicated broker.

**Comment by timnolte** [comment]
Actually, something else seems to be going on because I was able to successfully use the `meross` [Node setup utility](https://github.com/bytespider/Meross/) to pair a Meross smart plug to my setup with the latest Mosquito MQTT/MQTT Broker/Meross LAN add-on setup. And I was never able to get this pairer app to work.

**Comment by albertogeniola** [comment]
Hi! 
How did you configure the APP? Manual login or Local Meross Addon (that is th first step you should have done )

**Comment by timnolte** [comment]
So, after having some problems with using the [Node setup utility](https://github.com/bytespider/Meross/issues/48) in setting up a Meross mss510 switch I went back to the Pairer to see if I could figure out a way to get it working. I did manage to get the switch paired with the [Meross LAN](https://github.com/krahabb/meross_lan) add-on and my Mosquito MQTT. I ended up just using the Manual User/Key Setup with just a '0' as the "User ID" and left the "User Key" as blank. It's still not clear to me what these keys actually represent. One thing that I also did was take note of how the Meross device sets it's Username & Password from my earlier smart plugin testing. I setup an HA User using that same sort of information by MD5 hashing the MAC Address and prepending `0_`. It's still not 100% clear to me that it's needed.

Between both the Meross LAN add-on instructions and this app there is a lot of fuzziness around some of these keys/values and what they really represent.

**Comment by timnolte** [comment]
Just wanted to post another update. Using an MQTT client(MQTT X specifically) I was able to confirm that the mss510 switch that I was able to successfully setup via MQTT is in fact using the MAC Address/MD5 Hash Mac Address account to authenticate with my MQTT instance. So that is indeed a requirement of the Meross over local MQTT setup, even with the mobile paring app.

**Comment by rcdailey** [comment]
I'm still a firm believer that this whole thing needs to be streamlined. I'm fortunate to have the Homekit functionality in my Meross garage door openers. I've been able to avoid using these integrations. But it would be nice to avoid Homekit in favor of an IP-based local only solution (Homekit relies on mDNS which bothers me).

**Comment by timnolte** [comment]
@rcdailey are you using Home Assistant or what is your preferred platform for controlling the Meross devices? Currently, with Home Assistant I am able to get IP-based local-only control working, although my preference would be for MQTT but I haven't been able to get the Custom Pairer app to successfully configure MQTT on at least 3 types of devices right now.
