### ISSUE TITLE
Wi-Fi password wrongly saved on app

### ISSUE THREAD

**Issue by lechercheur123** [albertogeniola/Custom-Meross-Pairer#11]
Hi,

Thank you for your app, it males things easier :)

But a have a small issue.

Context:
I have a mosquitto MQTT Broker on my local network.
I can successfuly pair my MSS310 socket to my local MQTT Broker, thanks to your app. During the pairing process, I checked the "Save for future use" checkboxes for the Wi-Fi password and the MQTT broker informations.

But, if I try to pair a second Meross device, the Wi-Fi password appears to be wrongly saved, and the pairing process failed (the Meross device can't find the Wi-Fi AP, as it doesn't have the right passphrase).

I put as an attachment a screenshot showing the "erronous" Wi-Fi password saved by the app.
![Screenshot_20220114-142749_Custom Pairer](https://user-images.githubusercontent.com/3647355/149523131-f71cf806-ae1e-4c7f-b294-9da800fa297e.jpg)

It looks like to be a (little) bug...

Best regards,

Lechercheur123

**Comment by albertogeniola** [comment]
Hi @lechercheur123 ,

thanks a lot for reporting this bug. I've currently released a newer version of the app: do you mind testing the latest one?

**Comment by lechercheur123** [comment]
The app crash immediatly after launching it, so I can't test the fix :)

**Comment by albertogeniola** [comment]
Hi! 
Which version are you testing? The 0.1.0 is out on the official store (not beta), you should try that one!

**Comment by lechercheur123** [comment]
Hi,
Ok, I updated the app once again, and I am now at version 0.0.1 (and not 0.1.0) from Google Play Store.
The app don't crash at boot anymore.
But, the fix don't work for me ;(
The saved Wi-Fi password still looks like a weird string, as in my previous screenshot.
And, if I try to pair the smart plug with my Wi-Fi using the saved password, it doesn't work.

**Comment by albertogeniola** [comment]
Hi @lechercheur123 ,

you're right: I can confirm there currently is a bug preventing the wifi password from being stored correctly. I'll apply a fix and release it with the next version. Thanks a lot for reporting the problem.

**Comment by albertogeniola** [comment]
Hi @lechercheur123 ,

Version `0.0.2` has been released on the Beta channel. Can you please test it and see if that's now working as expected?

**Comment by lechercheur123** [comment]
> Hi @lechercheur123 ,
> 
> Version `0.0.2` has been released on the Beta channel. Can you please test it and see if that's now working as expected?

Hi @albertogeniola,

Unfortunalty, it seems to be worse. I can't even pair a smart plug now. I tried with two different plugs many times, and I keep getting the same error.

I get this error:

![Screenshot_20220125-232526_Custom Pairer](https://user-images.githubusercontent.com/3647355/151070951-c3301cf4-b3ac-4ac9-8034-19ec4db2e2a1.jpg)

Is mobile data (LTE/4G) necessary faor pairing devices ?

I will sleep now :) (it is late in France)

Thank you for your work anyway !

**Comment by albertogeniola** [comment]
I'm sorry to hear that. 

In any case, I've fixed various bugs around: the latest version is 0.0.5. You should test that one.
Regarding 4G, that's not necessary if your broker is in the same LAN where the device is.

**Comment by lechercheur123** [comment]
Hello @albertogeniola,

Yes, I can once again pair my smart plugs with your app !

And the Wi-Fi passphrase saving functionnality seems to work like a charm now !

Thank you very much for your work !

I may have some other bugs, but I will open a new issue if needed 😃

**Comment by albertogeniola** [comment]
Glad to hear that. If you like, positive feedbacks on Google Play Store are welcome :)
