### ISSUE TITLE
Sign release APK?

### ISSUE THREAD

**Issue by IzzySoft** [albertogeniola/Custom-Meross-Pairer#13]
Currently, at releases there's an unsigned APK attached. While advanced users and developers surely can sign themselves, average users can't. Would you mind attaching a **signed** APK?

Besides, what licence is protecting the app? Your repo or the code do not say, so currently it's "all rights reserved" – which is a legally uncertain situation for potential contributors as well as for those wanting to re-use code from your app – and also for those who want to share your app with friends :wink:

**Comment by albertogeniola** [comment]
Hi @IzzySoft ,
I am not providing signed apps from GitHub as I am actively managing releases via Google Play Store. The apps I release here are only meant for advanced users who do not want to wait for Google Play Store validation or who want to "rollback" to a previous version (that's not possible via the PlayStore). Thus, for those use cases, I expect the users to know how to deal with code and APKs.

Regarding the license, you are right, I'll update he repo with the some more specific information about that.

**Comment by albertogeniola** [comment]
Licensing terms added in https://github.com/albertogeniola/Custom-Meross-Pairer/commit/81698bb70e83b13d6323da1a9c5df8cbf5f643ad .

**Comment by IzzySoft** [comment]
Thanks! So what about those users without access to Play – because they have a device not supporting that (Huawei etc), because not having a Google Account intentionally (e.g. avoiding GAFAM tracking), and so on? Speaking in a picture: you've got a free bird here but put it into a cage :wink: (beside the fact a **private** key IMHO should stay private, and not be given to an ad company – who can say what they might add one day :speak_no_evil:)

**Comment by albertogeniola** [comment]
Ok, I see there is a use case I was not considering: devices with no Google Play support. In that case, I might consider releasing signed APKs on this repo, if that works for you. In such a case, the user might still trust "untrusted sources" from their apps, right?

**Comment by IzzySoft** [comment]
Hi @albertogeniola, I see the pre-releases are signed now. Do you want me starting with those – or rather wait for the next release? Or would you add a signed APK to the last stable release, so I start with that (ignoring the pre-releases)?
