### ISSUE TITLE
MDL110M with custom broker

### ISSUE THREAD

**Issue by lcorsini** [albertogeniola/Custom-Meross-Pairer#15]
I'm trying to pair the above lamp, the idea is to use my mosquitto installation that already drives most of my devices (zigbee2mqtt hvacs and shellys) but i'm puzzled by the application use, if I go for manual API setup it asks me for User ID and key, I set them, it discovers the lamp AP, tries to configure but it just does nothing then, not even pairing to wifi

and there is nothing I can change to input my current mqtt address, any hint on this?
or I should simply give up and use homekit (which is fine but needs an ios device to pair the device to wifi)

**Comment by Gandulf78** [comment]
I have the same question. Is it possible to pair with my own MQTT server ? (mosquitto on docker, I cannot install the HA add-on). Thank you.

**Comment by albertogeniola** [comment]
Hi!
Unfortunately that's not supported and I have no plan to support that case.
