### ISSUE TITLE
App not installed as package appears to be invaild.

### ISSUE THREAD

**Issue by kisa72** [albertogeniola/Custom-Meross-Pairer#18]
Hi,
I'm pretty excited about the App,but unfortunately I'm getting the error in the subject line when I try to run the .apk.
I'm running Android 13 on a Nexus 5.
Any help would be much appreciated.
Thanks,
Markus

**Comment by stain3565** [comment]
same for me

**Comment by CristianT** [comment]
same for me with the Release v0.0.4
I installed this pre-release (https://github.com/albertogeniola/Custom-Meross-Pairer/releases/tag/dev-2427266550)
and worked for me.

**Comment by albertogeniola** [comment]
Hi all,
please try with the latest version: that should fix a number of compatiblity issues. 

Let me know if that doesn't.
