### ISSUE TITLE
MSH300HK Hub and Valve Support

### ISSUE THREAD

**Issue by KiraPC** [albertogeniola/Custom-Meross-Pairer#20]
Hello,

I would like to setup my meross smarthub to comunicate to my domestic mqtt broker, but I have a question.

I have the hub MSH300HK where the thermovalves are connected to.

If I configure the smarthub to connect to my brocker, how I can connect the valves to the hub?

Is this scenario tested?

**Comment by albertogeniola** [comment]
Hi @KiraPC ,
This scenario is still in development, However there's a way to make it work.
You should first pair your meross devices with the HUB using the official meross APP. Then, you can pair the HUB with the local-addon. The link between the valves and the HUB should persist. 

Let me know if that's working for you!

**Comment by albertogeniola** [comment]
Closing as no answer was received to my message. Feel free to re-open if needed!
