### ISSUE TITLE
app seems not work

### ISSUE THREAD

**Issue by ghedolo** [albertogeniola/Custom-Meross-Pairer#21]
1. i reset my device (meross 210)
   2. choose pair new device in the app
   3. the app find the device
   4. at the end of the paring process i get some device information
   (among the others :chip rtl8710cm , version 7.0.0 )
   5. i choose configure this device
      1. i select my ssid wifi name
      2. the wifi password field contains very long string
      "com.google.android.material.textfiled.....)
      i just erase it and write into my wifi password (i don't press CR)
      3. i check "use for future use"
      4. i press validate and proceed
         1. i get "connect to wifi...." and after a while : wifi validation
         error doble che credential....

i'm sure about my credentials (I use them to connect my phone to my wifi!)

any hints ?

i'm using a google pixel 6a,
the meroos work well with the meross app.

regards
luca

**Comment by albertogeniola** [comment]
Hi!
I believe you are using an old version of the app. You should upgrade to the latest version and try again. 
1. Uninstall the `custom Meross pairer app` from your smartphone
2. Install the app back, making sure to install the latest version available
3. Repeast the pairing attempt (you'll need to login first)

Let me know if the proble persists or if it's solved with the last version of the app.

**Comment by mooton85** [comment]
I'm having the exact same issue as above, I have 2x MSS310 and get the same issue on both.

I've got the latest version I can see on the play store installed v0.0.9rc1 and have the same issue with wifi validation and my phone is also a Pixel (6 Pro).

I've tried skipping the validation and entering the MQTT settings but then at the end of the process, the app successfully connects to the 310 and issues pairing command but fails again at the "connect to target wifi" stage.

**Comment by ghedolo** [comment]
after some tentive (e som andoid update and a wifi router repalcemente....) now  it's fork fine.
My app version 0.0.9rc1

But the mqtt protocol of merross is so evil ...

**Comment by mooton85** [comment]
Got it working, suspect it was something my end but no idea what. It's worked when I've attempted it again this morning

**Comment by albertogeniola** [comment]
I'm glad it worked!
