### ISSUE TITLE
Mqtt server ports

### ISSUE THREAD

**Issue by stain3565** [albertogeniola/Custom-Meross-Pairer#22]
I have been attempting to pair meross ms426 surge protectors. My mosquitto mqtt has been up and working on my home assistant server for some time now. I have attached an image of my HA setup mosquitto config.

I expected to attach to port 8883 in the pairer but the search is finding a port 2001 available. If I set up an 8883 in the pairer, it does not pair successfully. The found 2001 does pair but then lost as how to proceed as this does not relate to my HA config. Images attached of found mqtt port and my manual set up. Any ideas?
![SmartSelect_20230305_141457_Home Assistant](https://user-images.githubusercontent.com/60330351/222966508-b5ce9b43-db22-4984-a950-2c1a1fc5ea7d.jpg)
![SmartSelect_20230305_141556_Home Assistant](https://user-images.githubusercontent.com/60330351/222966510-a7431993-d5e4-4f11-9b67-2366135eddd1.jpg)
![SmartSelect_20230305_141626_Custom Pairer](https://user-images.githubusercontent.com/60330351/222966512-85b900a3-0b78-4801-93a4-5a569837a9ad.jpg)
![SmartSelect_20230305_142728_Custom Pairer](https://user-images.githubusercontent.com/60330351/222966513-fd7e978a-010d-4f44-8954-ca9a0387011f.jpg)

**Comment by albertogeniola** [comment]
Hi @stain3565,
are you using the [Meross Local Broker Addon](https://github.com/albertogeniola/ha-meross-local-broker )?
That addon integrates a fully working MQTT broker and API endpoint: the pairer is designed to work with that and you don't need to use another broker (your MQTT broker).

Is there any specific reason why you need to use your mosquitto server?

**Comment by albertogeniola** [comment]
Closing as stale. Feel free to re-open if needed.
