### ISSUE TITLE
iphone user

### ISSUE THREAD

**Issue by vandlol** [albertogeniola/Custom-Meross-Pairer#23]
hey there - i would really like to pair my meross plugs to my local meross instance - but i cant seem to find a solution for pairing when using an iphone. i noticed the plug comes with a minimal webui available on 10.10.10.1 in the ad-hoc network it spawns when pairing - any chance to get it to join my local network without using the official app or needing an android phone?

**Comment by vandlol** [comment]
update: bluestacks doesnt work either, app starts fine, local login works, but cant find the plug, eventho i can open 10.10.10.1 in my browser - seems to be some issue with needing to actually run on a phone and connect to the network.

**Comment by albertogeniola** [comment]
Hi! 
iOS is not in scope at the moment. You'd better use other command-line tools like the[ bytespider's tool](https://github.com/bytespider/Meross) to do so.
