### ISSUE TITLE
Device Key ? 

### ISSUE THREAD

**Issue by Write** [albertogeniola/Custom-Meross-Pairer#24]
Hi, my Meross_Lan integration find automatically the freshly paired Meross devices, but I can't find the Device_Key ? Is there a way to find it ? 

I tried to use your plugin and set to a "custom" broker, but it won't connect to Local Meross Broker, hence why I'm asking if there's a way to retrieve device_key,

Thanks

**Comment by rubixcubez** [comment]
+1, I don't know how to get the device key either.

**Comment by Write** [comment]
> +1, I don't know how to get the device key either.

I found out it's way easier to ditch Meross local Broker and don't use custom pairer app. 

I setup my own mosquito server (HA Broken can't allow anonymous) via Docker, and paired manually with this tutorial : https://github.com/bytespider/Meross/wiki/MQTT

Then, the device will simply be discovered via Meross_Lan https://github.com/krahabb/meross_lan integration, and the key will simply be empty ! 

As for the Mosquitto container, I used this one : https://github.com/vvatelot/mosquitto-docker-compose

And simply mounted a volume with the certs (That you create during the tutorial).

The docker-compose.yaml simply look like this : 

![image](https://github.com/albertogeniola/Custom-Meross-Pairer/assets/541722/32f4eff2-c38c-4ecb-949d-7320c9c2b71d)

**Comment by krahabb** [comment]
@Write,
the device key is stored in the Meross cloud profile and you could use some `curl` to actually login to the meross cloud infrastructure and get this information or, in `meross_lan`, use the feature that allows you to recover the device key from the cloud profile automatically (so you don't have to tinker with manual message formatting and the likes)
I guess there are many other tools that, once provided with username/password for the Meross account could grab your device key without too much effort.

[Here](https://github.com/albertogeniola/MerossIot/wiki/HTTP-APIs) the background on the cloud login procedure

**Comment by Write** [comment]
> @Write,
> 
> the device key is stored in the Meross cloud profile and you could use some `curl` to actually login to the meross cloud infrastructure and get this information or, in `meross_lan`, use the feature that allows you to recover the device key from the cloud profile automatically (so you don't have to tinker with manual message formatting and the likes)
> 
> I guess there are many other tools that, once provided with username/password for the Meross account could grab your device key without too much effort.
> 
> 
> 
> [Here](https://github.com/albertogeniola/MerossIot/wiki/HTTP-APIs) the background on the cloud login procedure
> 
> 

Well, I know about cloud key, but tje whole point of this custom pairer app is to **not login** w/ meross cloud, since you pair it with your own MQTT Broker instead of Meross one. 
Now, I don't know why this app (Custom Pairer Tool) assign an unknown key (that is not retrievable trough the cloud, since you never logged in trough meross in the first place).
Anyway my method allows your device to have **an empty key**, as such Meross_Lan plugin will work.

**Comment by krahabb** [comment]
> Well, I know about cloud key, but tje whole point of this custom pairer app is to **not login** w/ meross cloud, since you pair it with your own MQTT Broker instead of Meross one. Now, I don't know why this app (Custom Pairer Tool) assign an unknown key (that is not retrievable trough the cloud, since you never logged in trough meross in the first place). Anyway my method allows your device to have **an empty key**, as such Meross_Lan plugin will work.

Right..I thought the meross pairer app would allow you to set the key (or leave it empty) and you were instead troubling getting a Meross cloud paired device key....
My misunderstanding ;)

**Comment by Write** [comment]
> > Well, I know about cloud key, but tje whole point of this custom pairer app is to **not login** w/ meross cloud, since you pair it with your own MQTT Broker instead of Meross one. Now, I don't know why this app (Custom Pairer Tool) assign an unknown key (that is not retrievable trough the cloud, since you never logged in trough meross in the first place). Anyway my method allows your device to have **an empty key**, as such Meross_Lan plugin will work.
> 
> Right..I thought the meross pairer app would allow you to set the key (or leave it empty) and you were instead troubling getting a Meross cloud paired device key.... My misunderstanding ;)

To be fair, I have absolutely no Idea why this custom pairer app add a custom key, since the default way of doing the same thing  (without any app + custom broker) (https://github.com/bytespider/Meross/wiki/MQTT) add an empty key (which was my solution in the end).

**Comment by albertogeniola** [comment]
Hi @Write ,
I am not sure I understand the exact issue here, but please let me state the following.

> To be fair, I have absolutely no Idea why this custom pairer app add a custom key, since the default way of doing the same thing (without any app + custom broker) (https://github.com/bytespider/Meross/wiki/MQTT) add an empty key (which was my solution in the end).

**This app was born to make sure people could use the Meross HA Addon.**  And, to ensure maximum compatiblity with the library, the Addon mimics exactly what the Meross cloud does. In other words, the addon generates an ID+cloudkey for the user (as the Meross Cloud does) and allows the pairer app to log-in in you "HA Meross Private cloud" (that's far from being a private cloud, but you can look at it that way). Of course, if you didn't use the HA Addon, you don't see any of it, and that's why you are so confused. 

Now, there are still methods to customize the cloud-key and avoid logging in at all. You just have to select "Manual user/key setup" in the first screen of the app, and that will bring you here:

<img height=800 src="https://github.com/albertogeniola/Custom-Meross-Pairer/assets/4648843/a65246b3-bb38-4ef5-9d49-0df10897f965">

<img height=800 src="https://github.com/albertogeniola/Custom-Meross-Pairer/assets/4648843/c043da86-8087-4597-bca6-f28224a29b6a">

In any case, "power users" like you are better going directly via CURL/APIs, which have been documented in details [here](https://albertogeniola.github.io/MerossIot/meross-protocol.html). Pairing with a custom broker is just a matter of sending a POST request via CURL with the right payload!

**Comment by Write** [comment]
> Hi @Write , I am not sure I understand the exact issue here, but please let me state the following.
> 
> > To be fair, I have absolutely no Idea why this custom pairer app add a custom key, since the default way of doing the same thing (without any app + custom broker) (https://github.com/bytespider/Meross/wiki/MQTT) add an empty key (which was my solution in the end).
> 
> **This app was born to make sure people could use the Meross HA Addon.** And, to ensure maximum compatiblity with the library, the Addon mimics exactly what the Meross cloud does. In other words, the addon generates an ID+cloudkey for the user (as the Meross Cloud does) and allows the pairer app to log-in in you "HA Meross Private cloud" (that's far from being a private cloud, but you can look at it that way). Of course, if you didn't use the HA Addon, you don't see any of it, and that's why you are so confused.
> 
> Now, there are still methods to customize the cloud-key and avoid logging in at all. You just have to select "Manual user/key setup" in the first screen of the app, and that will bring you here:
> 
> <img alt="" height="800" src="https://private-user-images.githubusercontent.com/4648843/293806266-a65246b3-bb38-4ef5-9d49-0df10897f965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMzc4ODAsIm5iZiI6MTcwNDIzNzU4MCwicGF0aCI6Ii80NjQ4ODQzLzI5MzgwNjI2Ni1hNjUyNDZiMy1iYjM4LTRlZjUtOWQ0OS0wZGYxMDg5N2Y5NjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMjMxOTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDVmYzAxMTJhMTBlNDVkODFjMjY2MTZhOTcxODljNjA1YWUxMmFmNmUyOGU4NjNmOTBjN2VlZGM1OTdhOGQ4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5jYoAkyisyI2bCUgfPDo91NxFae89iWlq-zOobZ01qM"> <img alt="" height="800" src="https://private-user-images.githubusercontent.com/4648843/293806265-c043da86-8087-4597-bca6-f28224a29b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMzc4ODAsIm5iZiI6MTcwNDIzNzU4MCwicGF0aCI6Ii80NjQ4ODQzLzI5MzgwNjI2NS1jMDQzZGE4Ni04MDg3LTQ1OTctYmNhNi1mMjgyMjRhMjliNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMjMxOTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ2ZjViZTJmZTBhNWQ5NDY5ZjI3MTc2Mjk5MjcyOTRjYjkyZmI4MTVlMzdjZjc0MGJmODljOGUwOWNkNDQyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5KO1BgKF--dmiP8jU73UF1sHFNxnXpTfs8zvxAU14a8">
> In any case, "power users" like you are better going directly via CURL/APIs, which have been documented in details [here](https://albertogeniola.github.io/MerossIot/meross-protocol.html). Pairing with a custom broker is just a matter of sending a POST request via CURL with the right payload!

Thanks. Well I was missing the Manuel USER/KEY setup indeed, guess it could've fixed my issue back then.
Anyway thank you for answering.
