### ISSUE TITLE
Release v0.0.10 apk invalid 

### ISSUE THREAD

**Issue by Raffaele-dot** [albertogeniola/Custom-Meross-Pairer#28]
Hi, release v0.0.10 apk It cannot be installed because the package seems invalid. Attached snapshot of android message.
![Screenshot_20241115_012123_Package installer](https://github.com/user-attachments/assets/c477afa9-10fd-41a6-8889-e11f1f10f21d)

**Comment by albertogeniola** [comment]
Hi @Raffaele-dot ,

are you installing the aab or the apk?

**Comment by Raffaele-dot** [comment]
Hi @albertogeniola, I have tried to install the apk

**Comment by albertogeniola** [comment]
Alright. It looks like the previous APK had an error. Can you please re-download it and test it again?
Link [here](https://github.com/albertogeniola/Custom-Meross-Pairer/releases/download/v0.0.10/MerossPairer.apk)

**Comment by Raffaele-dot** [comment]
It works, thanks
