### ISSUE TITLE
MQTT User name 

### ISSUE THREAD

**Issue by erte1** [albertogeniola/Custom-Meross-Pairer#6]
Hello!  Does this config allow you to use a custom username when logging into the MQTT host?  A result of the other pairing tools I've seen keep the username as the mac address.  This causes issues with login as HA MQTT 6.0 has a bug where it does not accept special characters in the username.

**Comment by albertogeniola** [comment]
Hi @erte1 ,
No it won't, as any other pairing tool. The username is filled in by the hardware device with its Mac address when it initiates the connection to the mqtt server that the pairing app sends to the hardware device. In other words, you should flash/hack the firmware of the hardware device to accomplish that.

Don't watery though: I am working on a custom addon with integrated mqtt server for HA which will work smoothly ;)
